version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend